### ISSUE TITLE
How to decorate `ActiveRecord::Base`

### ISSUE THREAD

**Issue by doits** [EPI-USE-Labs/activesupport-decorators#1]
I'm trying to decorate `ActiveRecord::Base` with the following file:

```
# app/decorators/active_record/base_decorator.rb
class ActiveRecord::Base
  raise 'error' # so I see the decorator loaded this file
end
```

My initializer looks like this:

```
# config/initializers/decorators.rb
ActiveSupportDecorators.paths << File.join(Rails.application.root, 'app/decorators/**')
```

But it looks like it is never decorated because no error is raised. Other decorator in `app/decorators/models/model_name_decorator.rb` are loaded, though. Is it not possible to decorate `ActiveRecord::Base`?

**Comment by pierre-pretorius** [comment]
Hi @doits

This gem hooks into the autoloading mechanism of ActiveSupport which means that anything which is loaded by referencing a constant instead of using a `require` statement is decoratable.  To get a list of what that is in your application, run the following in the rails console:

```
ActiveSupport::Dependencies.autoload_paths
```

ActiveRecord and Rails itself is not loaded by ActiveSupport.  The only way to decorate code that is loaded by a normal ruby `require` statement will be to eager load the decorators after application startup which is basically exactly the same as placing the `base_decorator.rb` in the `config/initializers` directory.

Can you think of a good way to support eager loading of decorators for things that isn't loaded by ActiveSupport that will still be easy enough for anyone to understand?

**Comment by doits** [comment]
Hmm ... if I understand it correctly, those classes like `ActiveRecord::Base` are not reloaded in development mode anyway (like normal models/controllers etc). This means it should be enough to require a decorator for these classes once on startup?

In this case there could be a second path for `ActiveSupportDecorators`, maybe something like:

```
ActiveSupportDecorators.preload_paths << ...
```

(a good name still to be decided). Things inside these paths are always required once during the initialization process (after `ActiveRecord::Base` are loaded etc. but before eager loading app`s models/controllers in production etc).

An alternative is to have files with the suffix `_decorator_once.rb` (or similar) in the normal `ActiveSupportDecorators.paths` to be loaded like this instead of having to introduce the new `preload_paths` option. Then one could simply drop files into the normal locations with this special suffix.

Both approaches would mean that the gem requires some files after base Rails is initialized without using the `ActiveSupport` way.

**Comment by doits** [comment]
Short update: I simple require my decorators of `ActiveSupport::Base` etc. by hand once on start and it works like a charm for 16 days now.

```
initializer :decorate_rails, before: :load_environment_hook do
  Dir[...dir of decorators...].each { |file| require file }
end
```
